[package]
name = "flappy"
version = "0.1.0"
authors = ["mobile-bungalow <pwmay@ucsc.edu>"]
edition = "2018"

[dependencies]
vecmath = "1.0"
piston_window = "0.94.0"
pistoncore-input = "0.28.0"
piston = "0.44.0"
fps_counter = "1.0.0"
pistoncore-glutin_window = "0.61.0"
piston2d-graphics = "0.32.0"
rand = "0.6.5"
piston2d-sprite = "0.55.0"
piston2d-opengl_graphics = "0.65.0"

